### PR TITLE
Surface GraphQL errors in NewRelic.

### LINKED ISSUE #54: Log/surface errors
This thread: https://github.com/artsy/force-private/pull/3774#discussion_r44986905

Basically, I think we should be logging whenever leafs are erroring (for a particular query). That way, instead of waiting to notice that something is broken or missing somewhere down the line, we can stay more on top of inconsistencies in our data or API responses, etc.

Maybe those queries should actually return non-successful status codes and it can be logged in NewRelic? If we want them to still be successful in prod, maybe we can have some middleware that sends any errors and the related queries to NewRelic or wherever.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #54.

This makes it so that errors in queries made by any client (Force or Eigen) all surface in NewRelic, allowing us to fix data issues sooner.

* Also upgrades the following dependencies:
  - `graphql-js` to `0.4.16` (still an old version)
  - `express-graphql` to 0.4.8 
* And replaces `should.js` with `expect.js`.

### CODE REVIEW

File: lib/graphql-error-handler.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+let graphqlErrorHandler = null;
+
+if (process.env.NEW_RELIC_LICENSE_KEY) {
+  const newrelic = require('newrelic');
+  graphqlErrorHandler = error => {
+    newrelic.noticeError(error, { graphql: true });
```
Comment (alloy) [inline lib/graphql-error-handler.js]: @craigspaeth There’s a bunch of test failures that I’ll have to investigate first, but wanted to get some eyes on this production/NewRelic code otherwise.

**Comment by alloy** [comment]
Hmm, it appears that `object.should` is `undefined`, which is what’s leading to these failures (or at least the majority of them).

```js
console.log(Object.prototype.should);
console.log(data.should);
```

```
Assertion { obj: {}, anyOne: false, negate: false, params: { actual: {} } }
undefined
```

I have no clue how that’s triggered by my changes. Suggestions?

File: lib/graphql-error-handler.js (hunk 1 above)
Comment (craigspaeth) [inline lib/graphql-error-handler.js]: This looks good!

One thing to note: NewRelic says that you can tag error with the `noticeError(error, { tag: true })` API... but I couldn't find a way to filter it out in their UI. So instead I ended up having to create my own error "type". Which you can see [here](https://github.com/artsy/artsy-newrelic/blob/master/index.js#L13), but I think you can actually just set the `name` property of the error, e.g. `error.name = 'GraphQLError`, to achieve the same thing.

**Comment by craigspaeth** [comment]
😮  I don't see anything in your PR that would cause should.js to not be loaded. It should be included in mocha via [this line](https://github.com/artsy/metaphysics/blob/master/test/mocha.opts#L1). Maybe we need to clear Semaphore's dependency cache? I'll kick it for good measure.

**Comment by alloy** [comment]
I reproduce it locally as well :/

File: lib/graphql-error-handler.js (hunk 1 above)
Comment (alloy) [inline lib/graphql-error-handler.js]: Wouldn’t that mask the name in the error message https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name ?

Comment (craigspaeth) [inline lib/graphql-error-handler.js]: It would, so if you want to retain those original error names than leave it as is. Just noting that NewRelic's UI won't actually take that `{ graphql: true }` property into consideration...

image

Hence the error name hack to work around the NR limitation.

**Comment by alloy** [comment]
I’m seeing this issue on Node 5.11.1, which I believe is what MP on deployment uses, and 6.2.1. It seems to be caused by the dependencies changes.

It’s weird, though, that @craigspaeth wasn’t able to reproduce this problem on Node 6.x.x.

**Comment by alloy** [comment]
Ok, based on some testing, what I _think_ happens is that some library code ensures that the result object from a query has **no** properties other than those in the resulting payload. That is, `Object.prototype.should` is being removed/excluded from the response object.

I tested this by adding a property to `Object.prototype`, which was also undefined on the response object.

**Comment by alloy** [comment]
Yup, in newer graphql-js versions the response objects are created with `Object.create(null)`, i.e. it does not inherit from `Object`. I think the most reliable/consistent fix for this would be to switch from `object.should.eql(…)` to `expect(object).to.eql(…)`.

Raise objections now or forever hold your peace.

**Comment by alloy** [comment]
@craigspaeth Done and green 👍

File: lib/graphql-error-handler.js (hunk 1 above)
Comment (alloy) [inline lib/graphql-error-handler.js]: I decided to not add the error cloning right now, because I’m thinking that the tagging might not actually be that relevant in this case.

**Comment by craigspaeth** [comment]
Good detective work @alloy! Shoot, I had a feeling that should's way of extending Object.prototype was going to become a problem at some point 🙁

**Comment by alloy** [comment]
It lead me to learning a few new things!

**Comment by alloy** [comment]
@craigspaeth Do you have a suggestion about how to test this on staging and verify it shows up in NewRelic?

**Comment by alloy** [comment]
Ok, I am triggering an error with this query:

```graphql
{
	artwork(id: "michael-dopp-untitled-blue-grey-grid-2") {
    partner {
      id
    }
  }
}
```
